<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ScheduleICompanion.ClonalCultivation</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\net6\MelonLoader.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\net6\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.Runtime"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppScheduleOne.Core"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\Il2CppScheduleOne.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppFishNet.Runtime"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\Il2CppFishNet.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppSteamworks"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\Il2Cppcom.rlabrecque.steamworks.net.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2Cppmscorlib" Condition="Exists('$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll')"><HintPath>$(ScheduleIGameDirectory)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
